//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poll_Maintenance
    {
        public Poll_Maintenance()
        {
            this.Poll_Questions = new HashSet<Poll_Questions>();
            this.Poll_Statistics = new HashSet<Poll_Statistics>();
            this.Poll_Users = new HashSet<Poll_Users>();
        }
    
        public int PollId { get; set; }
        public string PollTitle { get; set; }
        public string PollDescription { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> PollOwner { get; set; }
        public Nullable<int> ResultID { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> TotalVotesExpected { get; set; }
        public Nullable<int> ActualVotesSubmitted { get; set; }
        public Nullable<int> TotalDidNotVote { get; set; }
    
        public virtual Poll_Results Poll_Results { get; set; }
        public virtual Poll_Status Poll_Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<Poll_Questions> Poll_Questions { get; set; }
        public virtual ICollection<Poll_Statistics> Poll_Statistics { get; set; }
        public virtual ICollection<Poll_Users> Poll_Users { get; set; }
    }
}
