//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poll_Questions
    {
        public Poll_Questions()
        {
            this.Poll_Question_Options = new HashSet<Poll_Question_Options>();
            this.Poll_Transactions = new HashSet<Poll_Transactions>();
        }
    
        public int QuestionID { get; set; }
        public string QuestionDescription { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> PollID { get; set; }
        public Nullable<System.DateTime> ModifiedDate_ { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    
        public virtual Poll_Maintenance Poll_Maintenance { get; set; }
        public virtual ICollection<Poll_Question_Options> Poll_Question_Options { get; set; }
        public virtual ICollection<Poll_Transactions> Poll_Transactions { get; set; }
    }
}
