//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poll_Statistics
    {
        public int PollStatisticsID { get; set; }
        public Nullable<int> PollID { get; set; }
        public Nullable<int> OptionID { get; set; }
        public Nullable<int> TotalWeighedVotes { get; set; }
    
        public virtual Poll_Maintenance Poll_Maintenance { get; set; }
        public virtual Poll_Options Poll_Options { get; set; }
    }
}
