//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voting_types
    {
        public Voting_types()
        {
            this.Poll_Users = new HashSet<Poll_Users>();
        }
    
        public int VotingTypeID { get; set; }
        public string VotingTypeDescription { get; set; }
        public string Comments { get; set; }
    
        public virtual ICollection<Poll_Users> Poll_Users { get; set; }
    }
}
