//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amdox.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Partner_Types : IPartner_Types
    {
        [Key]
        public int PTID { get; set; }
        public string PartnerTypeDescription { get; set; }
        public Nullable<int> WeightedVote { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    }
}
