//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amdox.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Poll_Users : IPoll_Users
    {
        [Key]
        public int PollUserID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> VotingTypeID { get; set; }
        public Nullable<int> PollId { get; set; }
        public Nullable<int> PartnerTypeID { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> IsProxySet { get; set; }
    
    }
}
