//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amdox.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Poll_Questions : IPoll_Questions
    {
        [Key]    
        public int QuestionID { get; set; }
        public string QuestionDescription { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> PollID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<int> ResultID { get; set; }

        public Nullable<bool> IsAccepted { get; set; }

        public Nullable<bool> IsPublished { get; set; }
    
    }
}
