//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amdox.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Poll_Question_Options : IPoll_Question_Options
    {
        [Key]
        public int PQID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> OptionID { get; set; }
    
    }
}
