//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amdox.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Poll_Statistics : IPoll_Statistics
    {
        [Key]
        public int PollStatisticsID { get; set; }
        public Nullable<int> PollID { get; set; }
        public Nullable<int> OptionID { get; set; }
        public Nullable<int> TotalWeighedVotes { get; set; }
        public int QuestionID { get; set; }

        public Nullable<int> TotalVotes { get; set; }

        public Nullable<decimal> TotalWeighedVotesPercentage { get; set; }

        public Nullable<decimal> TotalVotesPercentage { get; set; }
    
    }
}
