//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amdox.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Poll_Maintenance : IPoll_Maintenance
    {
        [Key]    
        public int PollId { get; set; }
        public string PollTitle { get; set; }
        public string PollLongDescription { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> PollOwner { get; set; }        
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> TotalVotesExpected { get; set; }
        public Nullable<int> ActualVotesSubmitted { get; set; }
        public Nullable<int> TotalDidNotVote { get; set; }
        public string PollShortDescription { get; set; }
        public Nullable<int> PollType { get; set; }
        public Nullable<bool> IsAutoClose { get; set; }

        public Nullable<int> VoteTypePercentage { get; set; }

        public Nullable<int> TotalWeightedVotesExpected { get; set; }

        public Nullable<int> ActualWeightedVotesSubmitted { get; set; }

        public Nullable<int> TotalWeightedDidNotVote { get; set; }

        public Nullable<decimal> TotalDidNotVotePercentage { get; set; }

        public Nullable<decimal> TotalWeightedDidNotVotePercentage { get; set; }
    }
}
