//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amdox.DataModel
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserDetail : IUserDetail
    {
        [Key]
        public int UserDetailsID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> PartnerTypeID { get; set; }
        public Nullable<bool> IsInternationalPartner { get; set;  }
        public string OfficeLocation { get; set; }
        public Nullable<System.DateTime> ResignationDate { get; set; }
        public Nullable<bool> isResigned { get; set; }
        public Nullable<System.DateTime> DateLeft { get; set; }
        public string EmailAddress { get; set; }
        public string Title { get; set; }
        public bool? IsEmailNotificationRequired{ get; set; }
        
    }
}
