//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amdox.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public interface IPartner_Types
    {

        int PTID { get; set; }
        string PartnerTypeDescription { get; set; }
        Nullable<int> WeightedVote { get; set; }
        Nullable<bool> IsEnabled { get; set; }
    
    }
}
