//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amdox.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public interface IPoll_Questions
    {

        int QuestionID { get; set; }
        string QuestionDescription { get; set; }
        Nullable<int> Sequence { get; set; }
        Nullable<int> PollID { get; set; }
        Nullable<System.DateTime> ModifiedDate { get; set; }
        Nullable<bool> IsEnabled { get; set; }
        Nullable<int> ResultID { get; set; }

        Nullable<bool> IsAccepted { get; set; }

        Nullable<bool> IsPublished { get; set; }

    }
}
