//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amdox.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public interface IPoll_Statistics
    {
        int PollStatisticsID { get; set; }
        Nullable<int> PollID { get; set; }
        Nullable<int> OptionID { get; set; }
        Nullable<int> TotalWeighedVotes { get; set; }
        int QuestionID { get; set; }
        Nullable<int> TotalVotes { get; set; }
        Nullable<decimal> TotalWeighedVotesPercentage { get; set; }

        Nullable<decimal> TotalVotesPercentage { get; set; }

    }
}
