//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amdox.DataModel
{
    using System;
    using System.Collections.Generic;

    public interface IPoll_Documents
    {
         int DocumentID { get; set; }
         string DocumentNumber { get; set; }
         string DocumentURL { get; set; }
         Nullable<int> UploadedBy { get; set; }
         Nullable<System.DateTime> UploadedDate { get; set; }
         Nullable<int> PollID { get; set; }
         Nullable<int> QuestionID { get; set; }
         bool IsEnabled { get; set; }
         string FileName { get; set; }
         string ContentType { get; set; }
        
    }
}
