//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amdox.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public interface IUser
    {

        int UserID { get; set; }
        string UserName { get; set; }
        string Initial { get; set; }
        string Department { get; set; }
        Nullable<bool> IsEnabled { get; set; }
        Nullable<bool> IsAllowedToVote { get; set; }
        string Password { get; set; }
        int? OrganisationId { get; set; }

    }
}
