//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amdox.DataModel
{
    using System;
    using System.Data.Entity;

    public interface IVoteContext
    {
        DbSet<IPartner_Types> Partner_Types { get; set; }
        DbSet<IPoll_Maintenance> Poll_Maintenance { get; set; }
        DbSet<IPoll_Options> Poll_Options { get; set; }
        DbSet<IPoll_ProxyUser> Poll_ProxyUser { get; set; }
        DbSet<IPoll_Question_Options> Poll_Question_Options { get; set; }
        DbSet<IPoll_Questions> Poll_Questions { get; set; }
        DbSet<IPoll_Results> Poll_Results { get; set; }
        DbSet<IPoll_Statistics> Poll_Statistics { get; set; }
        DbSet<IPoll_Status> Poll_Status { get; set; }
        DbSet<IPoll_Transactions> Poll_Transactions { get; set; }
        DbSet<IPoll_Users> Poll_Users { get; set; }
        DbSet<IUser_Types> User_Types { get; set; }
        DbSet<IUserDetail> UserDetails { get; set; }
        DbSet<IUser> Users { get; set; }
        DbSet<IVoting_types> Voting_types { get; set; }
        DbSet<IPoll_Documents> Poll_Documents { get; set; }
    }
}
